### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by flyingfisch** [flyingfisch/FischBotDiscord-csharp#1]

**Comment by MattTheDev** [comment]
What kind of logging were you thinking?

**Comment by flyingfisch** [comment]
@MattTheDev Still thinking about it which is why I haven't started this yet. The bot is running on a VPS, it would be cool if I could have a web interface to check the logs, so right now I'm researching logging solutions that would give me that. I think I want to have a LoggingService and ILoggingService in any case, so that the logger could be implementation agnostic. What are your thoughts? Do you have any suggestions?

**Comment by flyingfisch** [comment]
I've used Serilog before and liked it... looking at it now it might be what I need. Researching sinks to see what would be appropriate to use for this.

**Comment by flyingfisch** [comment]
new relic appears to be a good free solution for the bot's current scale

**Comment by flyingfisch** [comment]
So I'm thinking Serilog with the NewRelic sink?

**Comment by flyingfisch** [comment]
hmm just created a NewRelic account, I don't like how feature-heavy it is. We really just need a super simple interface to read logs and that's it. I don't need telemetry and stuff.

**Comment by flyingfisch** [comment]
I've used seq in the past, I'm looking for something like that

**Comment by MattTheDev** [comment]
I use NewRelic at my day job - it's a sledgehammer approach for sure .. but when the bot scales, might be nice to see telemetry, usage, etc? I've got a bot I've ran for 5+ years now .. you mentioning NewRelic kind of makes me want to add it to mine haha.

If I can help with logging here, let me know! Enjoyed helping out with the other tasks.

**Comment by flyingfisch** [comment]
Want to jump in a discord call and talk about it?

**Comment by flyingfisch** [comment]
I added a Serilog logger, I'm going to add a new issue for figuring out a better sink or possibly writing my own logging dashboard.
