### ISSUE TITLE
Add support for the new slash commands Discord feature

### ISSUE THREAD

**Issue by flyingfisch** [flyingfisch/FischBotDiscord-csharp#49]

**Comment by ArmoryNode** [comment]
Greetings! I can take this one.

**Comment by flyingfisch** [comment]
@ArmoryNode thanks for taking a look at this. I hadn't researched it much and yeah, looks like that's still not merged in. I'm going to mark this one as blocked for now.

**Comment by flyingfisch** [comment]
@ArmoryNode if you're looking for something for Hacktoberfest, #43 or #44 might be interesting to you? Not trying to pressure you into taking those though, just thought I'd let you know in case you were still looking for something relatively isolated/simple.

I'll be out of town all weekend so if you have questions I'll try to get back to you on Monday.

Appreciate the research you did for this issue, I wish I could somehow make that count for your Hacktoberfest since it was definitely a useful contribution.

**Comment by quinchs** [comment]
The PR implements [Discord.Net Labs](https://github.com/Discord-Net-Labs/Discord.Net-Labs) which has its own package you can add while the pr is still under review. I'm actively working with the current maintainer to squash the last of the changes for main dnet.

**Comment by ArmoryNode** [comment]
@quinchs Hey thanks for the heads up! I really appreciate it.

**Comment by flyingfisch** [comment]
removed `blocked` tag since it looks like the slash commands PR has been merged.

**Comment by flyingfisch** [comment]
this currently depends on #66

**Comment by flyingfisch** [comment]
Created branch `49-add-slash-commands` for this
